# Generated by Django 4.0.4 on 2022-06-10 14:57

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'مزیت',
                'verbose_name_plural': 'مزایا',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.FileField(upload_to='', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='آدرس')),
                ('image', models.FileField(upload_to='', verbose_name='لوگو')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], max_length=8, verbose_name='وضعیت')),
                ('keyword', models.CharField(blank=True, max_length=300, null=True, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='متای توضیحات')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'مورد مصرف',
                'verbose_name_plural': 'موارد مصرف',
            },
        ),
        migrations.CreateModel(
            name='ProductVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ بازدید')),
                ('ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ip.ipaddress')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'بازدید محصول',
                'verbose_name_plural': 'بازدید های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='نظر')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], default='d', max_length=8, verbose_name='وضعیت')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='product.product', verbose_name='محصول')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductReply', to='product.productcomment', verbose_name='پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductComment_user', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده نظر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='آدرس')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], max_length=10, verbose_name='وضعیت')),
                ('keyword', models.CharField(blank=True, max_length=300, null=True, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='متای توضیحات')),
                ('subClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Child', to='product.productcategory', verbose_name='دسته مادر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='ProductCategory', to='product.productcategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(related_name='feature', to='product.feature', verbose_name='مزایا'),
        ),
        migrations.AddField(
            model_name='product',
            name='ip',
            field=models.ManyToManyField(blank=True, related_name='productIp', through='product.ProductVisit', to='ip.ipaddress', verbose_name='بازدید'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='product.producttag', verbose_name='برچسب ها'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.ManyToManyField(related_name='usage', to='product.usage', verbose_name='موارد مصرف'),
        ),
    ]
