# Generated by Django 4.0.4 on 2022-06-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_gallery_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(related_name='gallery', to='product.gallery', verbose_name='تصاویر بیشتر'),
        ),
    ]
