# Generated by Django 4.0.4 on 2022-06-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='post',
            new_name='product',
        ),
    ]
