# Generated by Django 4.0.4 on 2022-06-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_post_productcomment_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی های محصولات'},
        ),
    ]
