# Generated by Django 4.0.4 on 2022-06-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.FileField(null=True, upload_to='productCategory/', verbose_name='تصویر'),
        ),
    ]
