# Generated by Django 4.0.4 on 2022-07-01 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_options_product_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-publish'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی های محصولات'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'ordering': ['-publish'], 'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
    ]
