# Generated by Django 4.0.4 on 2022-07-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متای توضیحات'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='keyword',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='کلمات کلیدی'),
        ),
    ]
