# Generated by Django 4.0.4 on 2022-07-02 13:36

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='آدرس')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], max_length=8, verbose_name='وضعیت')),
                ('keyword', models.CharField(blank=True, max_length=300, null=True, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='متای توضیحات')),
                ('image', models.ImageField(null=True, upload_to='blog/', verbose_name='تصویر')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='متن مقاله')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='PostVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ بازدید')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='مقاله')),
                ('ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ip.ipaddress', verbose_name='')),
            ],
            options={
                'verbose_name': 'بازدید مقاله',
                'verbose_name_plural': 'بازدید های مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='نظر')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], default='d', max_length=8, verbose_name='وضعیت')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='blog.blog', verbose_name='مقاله')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reply', to='blog.blogcomment', verbose_name='پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcomment_user', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده نظر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='آدرس')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], max_length=10, verbose_name='وضعیت')),
                ('keyword', models.CharField(blank=True, max_length=300, null=True, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='متای توضیحات')),
                ('subClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Child', to='blog.blogcategory', verbose_name='دسته مادر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='Category', to='blog.blogcategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='blog',
            name='ip',
            field=models.ManyToManyField(blank=True, related_name='blogIp', through='blog.PostVisit', to='ip.ipaddress', verbose_name='بازدید'),
        ),
        migrations.AddField(
            model_name='blog',
            name='similar_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_category', to='blog.blogcategory', verbose_name='دسته بندی اصلی'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='blog.blogtag', verbose_name='برچسب ها'),
        ),
    ]
