# Generated by Django 4.0.4 on 2022-07-02 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['-publish'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی های مقالات'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'ordering': ['-publish'], 'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متای توضیحات'),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='keyword',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
    ]
