# Generated by Django 4.0.4 on 2022-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='iframe_link',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='like',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blog/', verbose_name='تصویر'),
        ),
    ]
